### ISSUE TITLE
Unit Tests: pkg/prm/exec

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/prm#102]
Unit tests cover:

- [x] When the tool is unavailable
- [x] When the tool is believed available and reports success
- [x] When the tool is believed available and reports failure
- [x] When the tool is believed available and the tool misbehaves
- [x] When the tool is believed available but not found in the backend

**Comment by david22swan** [comment]
Work to create test's has been completed, however in the progress it was discovered that the exec command itself was not functioning as we thought, i.e. while the failure of docker to run the command is properly returned as an error, the failure of the command itself is not.
