### ISSUE TITLE
Author Tool Config (Docker backend): Spec Puppet

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/prm#12]
Generate a tool configuration that will allow `rake spec` to be executed against the [puppetlabs-motd](https://github.com/puppetlabs/puppetlabs-motd) module.

**Acceptance Criteria:**

- [ ] `prm-config.yml` that will defines a tool that can exec `rspec` against a module
- [ ] Rspec spec tests execute successfully against the `puppetlabs-motd` module (NOTE: This can be tested standalone, invoking via Docker manually)
- [ ] Generate Dockerfile of container

This is investigative work to ensure that the `gem` configuration defined in [`prm-config.yml`](https://docs.google.com/document/d/1T0_gH1K7JnKP4qYKysfDCAHWHr9KZ0CCa0YZVnTeIwQ/edit#heading=h.hnv8vjlsqep9) will satisfy the requirements of an author.

**Comment by da-ar** [comment]
I was able to create a config and dockerfile from that config that performed the tasks as set out in the description. However upon widening the criteria to switch between Puppet versions holes started to show. 

Closing this ticket as the requirements were met. However additional work is required for a spec puppet tool to meet the requirements of the PRM.
