### ISSUE TITLE
Exec: Implement a timeout flag

### ISSUE THREAD

**Issue by michaeltlombardi** [puppetlabs/prm#54]
In the initial implementation of the exec command, a default timeout of 30 minutes was hard coded into the docker client initialization. This timeout should be configurable by the user at the cli in cases where an execution is expected to be much shorter or longer.

## Acceptance Criteria

- [x] The exec command has a timeout flag with a default value of 30 minutes
- [x] The child contexts spawned by the exec command adhere to this timeout
- [ ] Acceptance tests verify that an arbitrarily short timeout cuts execution short gracefully

**Comment by david22swan** [comment]
Acceptance test's for the exec command have yet to be implemented and are part of a separate piece of work
