### ISSUE TITLE
Stub `prm validate` command

### ISSUE THREAD

**Issue by sanfrancrisko** [puppetlabs/prm#7]
Implement `prm validate` command. This will:

- Execute the specified tool against the current working directory / specified tool dir
- Pass any flags specified on the command line to the tool
- Output in the specified output, defaulting to human readable / raw output from tool, if not specified

```sh
prm validate [--dir </path/to/code>] [--output json] <tool> <tool-flags> 
```

Examples:

```sh
prm validate rubocop
prm validate --dir /path/to/my/module rubocop
prm validate --dir /path/to/my/module rubocop --auto-correct
prm validate --dir /path/to/my/module --output json rubocop --auto-correct # Would require `needs_write_access = true` to be set
```

**Comment by da-ar** [comment]
The ticket only covers the first part of implementing the command. As per:
https://github.com/puppetlabs/prm/pull/33
